"""
Blog Post 180: How to Place Azure Firewall in a Hub-and-Spoke Network
"""

BLOG_POST = {'title': 'How to Place Azure Firewall in a Hub-and-Spoke Network',
 'coverImage': 'https://static.wixstatic.com/media/32fce1_6c1cc8bc82db46b998b61dc5273d7d99~mv2.png',
 'content': 'A useful Azure how-to should end with something you can operate, not just something '
            'that deployed once.\n'
            '\n'
            'This guide walks through **centralized network inspection for spoke traffic using a '
            'shared hub firewall** using **Azure Firewall**.\n'
            '\n'
            '## When To Use This Pattern\n'
            '\n'
            'Use this pattern when you need a repeatable way to configure **Azure Firewall** and '
            'explain the decision to another engineer later.\n'
            '\n'
            'The goal is not to click through the portal as fast as possible.\n'
            '\n'
            'The goal is to understand the resource, the security boundary, the validation step, '
            'and the operational owner.\n'
            '\n'
            '## Before You Start\n'
            '\n'
            'Confirm the subscription, resource group, region, naming standard, tags, and identity '
            'model before creating anything.\n'
            '\n'
            'Also confirm whether this change affects production traffic, data access, cost, or '
            'compliance.\n'
            '\n'
            'If it does, create the change record first and make rollback expectations explicit.\n'
            '\n'
            '## Steps\n'
            '\n'
            '1. Deploy Azure Firewall into a dedicated AzureFirewallSubnet in the hub VNet.\n'
            '\n'
            '2. Peer spoke VNets to the hub with the correct gateway and forwarding settings.\n'
            '\n'
            '3. Create route tables that send required traffic through the firewall.\n'
            '\n'
            '4. Build application and network rules around real traffic needs.\n'
            '\n'
            '5. Send firewall logs to Log Analytics for review.\n'
            '\n'
            '## Validate The Work\n'
            '\n'
            'Test traffic from a spoke workload and confirm the firewall sees and allows or denies '
            'the flow as expected.\n'
            '\n'
            'Validation is where many cloud guides get weak.\n'
            '\n'
            'Do not stop at a green deployment screen. Test from the same network, identity, '
            'pipeline, or application path that will use the service in real life.\n'
            '\n'
            '## Production Notes\n'
            '\n'
            'Central inspection is powerful, but bad routes can break everything. Roll out route '
            'changes carefully.\n'
            '\n'
            'Add tags, diagnostic settings, alert ownership, and documentation before calling the '
            'work finished.\n'
            '\n'
            'If the resource is important enough to deploy, it is important enough to monitor.\n'
            '\n'
            '## Common Mistakes\n'
            '\n'
            'The first mistake is deploying without knowing the owner.\n'
            '\n'
            'The second mistake is skipping least privilege because a broad role is faster.\n'
            '\n'
            'The third mistake is forgetting DNS, routing, logging, or cost review until after the '
            'first incident.\n'
            '\n'
            'Keep the implementation small, but make the operating model clear.\n'
            '\n'
            '## Bottom Line\n'
            '\n'
            '**Azure Firewall** is easier to support when the design is intentional.\n'
            '\n'
            'Build it with a clear purpose, validate the real path, and leave behind enough '
            'documentation that the next engineer can understand the decision.\n'
            '\n'
            '## Sources\n'
            '\n'
            'Microsoft Learn: https://learn.microsoft.com/en-us/azure/firewall/overview\n'
            '\n'
            '---\n'
            '\n'
            "*Stay radical, stay curious, and keep pushing the boundaries of what's possible in "
            'the cloud.*\n'
            '\n'
            '**Chriz**\n'
            '*Beyond Cloud with Chriz*',
 'excerpt': 'A practical Azure how-to for Azure Firewall: centralized network inspection for spoke '
            'traffic using a shared hub firewall.',
 'publish': True,
 'tags': ['Azure', 'Azure Firewall', 'Networking', 'Security']}
