"""
Blog Post 164: How to Use Workload Identity on Azure Kubernetes Service
"""

BLOG_POST = {'title': 'How to Use Workload Identity on Azure Kubernetes Service',
 'coverImage': 'https://static.wixstatic.com/media/32fce1_6c1cc8bc82db46b998b61dc5273d7d99~mv2.png',
 'content': 'A useful Azure how-to should end with something you can operate, not just something '
            'that deployed once.\n'
            '\n'
            'This guide walks through **AKS pods that access Azure resources through federated '
            'identity instead of static secrets** using **Azure Kubernetes Service**.\n'
            '\n'
            '## When To Use This Pattern\n'
            '\n'
            'Use this pattern when you need a repeatable way to configure **Azure Kubernetes '
            'Service** and explain the decision to another engineer later.\n'
            '\n'
            'The goal is not to click through the portal as fast as possible.\n'
            '\n'
            'The goal is to understand the resource, the security boundary, the validation step, '
            'and the operational owner.\n'
            '\n'
            '## Before You Start\n'
            '\n'
            'Confirm the subscription, resource group, region, naming standard, tags, and identity '
            'model before creating anything.\n'
            '\n'
            'Also confirm whether this change affects production traffic, data access, cost, or '
            'compliance.\n'
            '\n'
            'If it does, create the change record first and make rollback expectations explicit.\n'
            '\n'
            '## Steps\n'
            '\n'
            '1. Enable the OIDC issuer and workload identity features on the AKS cluster.\n'
            '\n'
            '2. Create or choose a managed identity for the workload.\n'
            '\n'
            '3. Create a federated identity credential that maps the Kubernetes service account to '
            'the managed identity.\n'
            '\n'
            '4. Annotate the service account and deploy the workload with that service account.\n'
            '\n'
            '5. Grant the managed identity least-privilege access to the Azure resource.\n'
            '\n'
            '## Validate The Work\n'
            '\n'
            'Check pod logs, token projection, and target resource audit logs to confirm the pod '
            'is using the expected identity.\n'
            '\n'
            'Validation is where many cloud guides get weak.\n'
            '\n'
            'Do not stop at a green deployment screen. Test from the same network, identity, '
            'pipeline, or application path that will use the service in real life.\n'
            '\n'
            '## Production Notes\n'
            '\n'
            'Do not grant one identity broad access for every namespace. Treat workload identity '
            'boundaries like application boundaries.\n'
            '\n'
            'Add tags, diagnostic settings, alert ownership, and documentation before calling the '
            'work finished.\n'
            '\n'
            'If the resource is important enough to deploy, it is important enough to monitor.\n'
            '\n'
            '## Common Mistakes\n'
            '\n'
            'The first mistake is deploying without knowing the owner.\n'
            '\n'
            'The second mistake is skipping least privilege because a broad role is faster.\n'
            '\n'
            'The third mistake is forgetting DNS, routing, logging, or cost review until after the '
            'first incident.\n'
            '\n'
            'Keep the implementation small, but make the operating model clear.\n'
            '\n'
            '## Bottom Line\n'
            '\n'
            '**Azure Kubernetes Service** is easier to support when the design is intentional.\n'
            '\n'
            'Build it with a clear purpose, validate the real path, and leave behind enough '
            'documentation that the next engineer can understand the decision.\n'
            '\n'
            '## Sources\n'
            '\n'
            'Microsoft Learn: '
            'https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview\n'
            '\n'
            '---\n'
            '\n'
            "*Stay radical, stay curious, and keep pushing the boundaries of what's possible in "
            'the cloud.*\n'
            '\n'
            '**Chriz**\n'
            '*Beyond Cloud with Chriz*',
 'excerpt': 'A practical Azure how-to for Azure Kubernetes Service: AKS pods that access Azure '
            'resources through federated identity instead of static secrets.',
 'publish': True,
 'tags': ['Azure', 'AKS', 'Workload Identity', 'Kubernetes']}
