"""
Blog Post 200: How to Use Managed Identity from an Azure Virtual Machine
"""

BLOG_POST = {'title': 'How to Use Managed Identity from an Azure Virtual Machine',
 'coverImage': 'https://static.wixstatic.com/media/32fce1_6c1cc8bc82db46b998b61dc5273d7d99~mv2.png',
 'content': 'A useful Azure how-to should end with something you can operate, not just something '
            'that deployed once.\n'
            '\n'
            'This guide walks through **a VM that authenticates to Azure services through managed '
            'identity instead of stored credentials** using **Managed Identities**.\n'
            '\n'
            '## When To Use This Pattern\n'
            '\n'
            'Use this pattern when you need a repeatable way to configure **Managed Identities** '
            'and explain the decision to another engineer later.\n'
            '\n'
            'The goal is not to click through the portal as fast as possible.\n'
            '\n'
            'The goal is to understand the resource, the security boundary, the validation step, '
            'and the operational owner.\n'
            '\n'
            '## Before You Start\n'
            '\n'
            'Confirm the subscription, resource group, region, naming standard, tags, and identity '
            'model before creating anything.\n'
            '\n'
            'Also confirm whether this change affects production traffic, data access, cost, or '
            'compliance.\n'
            '\n'
            'If it does, create the change record first and make rollback expectations explicit.\n'
            '\n'
            '## Steps\n'
            '\n'
            '1. Enable system-assigned or user-assigned managed identity on the VM.\n'
            '\n'
            '2. Grant the identity the required role on the target resource.\n'
            '\n'
            '3. Update scripts or applications to request tokens from the Azure identity '
            'endpoint.\n'
            '\n'
            '4. Remove stored credentials from the VM.\n'
            '\n'
            '5. Monitor target resource logs for identity-based access.\n'
            '\n'
            '## Validate The Work\n'
            '\n'
            'Run a test command from the VM that accesses the target resource using the managed '
            'identity.\n'
            '\n'
            'Validation is where many cloud guides get weak.\n'
            '\n'
            'Do not stop at a green deployment screen. Test from the same network, identity, '
            'pipeline, or application path that will use the service in real life.\n'
            '\n'
            '## Production Notes\n'
            '\n'
            'A compromised VM can use its managed identity. Keep VM hardening and role scope '
            'tight.\n'
            '\n'
            'Add tags, diagnostic settings, alert ownership, and documentation before calling the '
            'work finished.\n'
            '\n'
            'If the resource is important enough to deploy, it is important enough to monitor.\n'
            '\n'
            '## Common Mistakes\n'
            '\n'
            'The first mistake is deploying without knowing the owner.\n'
            '\n'
            'The second mistake is skipping least privilege because a broad role is faster.\n'
            '\n'
            'The third mistake is forgetting DNS, routing, logging, or cost review until after the '
            'first incident.\n'
            '\n'
            'Keep the implementation small, but make the operating model clear.\n'
            '\n'
            '## Bottom Line\n'
            '\n'
            '**Managed Identities** is easier to support when the design is intentional.\n'
            '\n'
            'Build it with a clear purpose, validate the real path, and leave behind enough '
            'documentation that the next engineer can understand the decision.\n'
            '\n'
            '## Sources\n'
            '\n'
            'Microsoft Learn: '
            'https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/overview\n'
            '\n'
            '---\n'
            '\n'
            "*Stay radical, stay curious, and keep pushing the boundaries of what's possible in "
            'the cloud.*\n'
            '\n'
            '**Chriz**\n'
            '*Beyond Cloud with Chriz*',
 'excerpt': 'A practical Azure how-to for Managed Identities: a VM that authenticates to Azure '
            'services through managed identity instead of stored credentials.',
 'publish': True,
 'tags': ['Azure', 'Managed Identity', 'Virtual Machines', 'Security']}
