"""
Blog Post 163: How to Roll Out Azure Front Door WAF Without Breaking Real Traffic
"""

BLOG_POST = {'title': 'How to Roll Out Azure Front Door WAF Without Breaking Real Traffic',
 'coverImage': 'https://static.wixstatic.com/media/32fce1_6c1cc8bc82db46b998b61dc5273d7d99~mv2.png',
 'content': 'A useful Azure how-to should end with something you can operate, not just something '
            'that deployed once.\n'
            '\n'
            'This guide walks through **a WAF policy that starts in detection, gets tuned with '
            'evidence, and moves toward prevention safely** using **Azure Web Application '
            'Firewall**.\n'
            '\n'
            '## When To Use This Pattern\n'
            '\n'
            'Use this pattern when you need a repeatable way to configure **Azure Web Application '
            'Firewall** and explain the decision to another engineer later.\n'
            '\n'
            'The goal is not to click through the portal as fast as possible.\n'
            '\n'
            'The goal is to understand the resource, the security boundary, the validation step, '
            'and the operational owner.\n'
            '\n'
            '## Before You Start\n'
            '\n'
            'Confirm the subscription, resource group, region, naming standard, tags, and identity '
            'model before creating anything.\n'
            '\n'
            'Also confirm whether this change affects production traffic, data access, cost, or '
            'compliance.\n'
            '\n'
            'If it does, create the change record first and make rollback expectations explicit.\n'
            '\n'
            '## Steps\n'
            '\n'
            '1. Create a WAF policy and attach managed rules that match the application risk '
            'profile.\n'
            '\n'
            '2. Start in detection mode so the team can observe rule matches.\n'
            '\n'
            '3. Send WAF logs to Log Analytics for review.\n'
            '\n'
            '4. Tune exclusions and custom rules with application owners.\n'
            '\n'
            '5. Move to prevention only after normal traffic has been reviewed.\n'
            '\n'
            '## Validate The Work\n'
            '\n'
            'Review WAF logs for blocked or matched requests and test known safe requests through '
            'the application.\n'
            '\n'
            'Validation is where many cloud guides get weak.\n'
            '\n'
            'Do not stop at a green deployment screen. Test from the same network, identity, '
            'pipeline, or application path that will use the service in real life.\n'
            '\n'
            '## Production Notes\n'
            '\n'
            'WAF is not a set-and-forget checkbox. Rule tuning needs ownership and regular '
            'review.\n'
            '\n'
            'Add tags, diagnostic settings, alert ownership, and documentation before calling the '
            'work finished.\n'
            '\n'
            'If the resource is important enough to deploy, it is important enough to monitor.\n'
            '\n'
            '## Common Mistakes\n'
            '\n'
            'The first mistake is deploying without knowing the owner.\n'
            '\n'
            'The second mistake is skipping least privilege because a broad role is faster.\n'
            '\n'
            'The third mistake is forgetting DNS, routing, logging, or cost review until after the '
            'first incident.\n'
            '\n'
            'Keep the implementation small, but make the operating model clear.\n'
            '\n'
            '## Bottom Line\n'
            '\n'
            '**Azure Web Application Firewall** is easier to support when the design is '
            'intentional.\n'
            '\n'
            'Build it with a clear purpose, validate the real path, and leave behind enough '
            'documentation that the next engineer can understand the decision.\n'
            '\n'
            '## Sources\n'
            '\n'
            'Microsoft Learn: '
            'https://learn.microsoft.com/en-us/azure/web-application-firewall/afds/afds-overview\n'
            '\n'
            '---\n'
            '\n'
            "*Stay radical, stay curious, and keep pushing the boundaries of what's possible in "
            'the cloud.*\n'
            '\n'
            '**Chriz**\n'
            '*Beyond Cloud with Chriz*',
 'excerpt': 'A practical Azure how-to for Azure Web Application Firewall: a WAF policy that starts '
            'in detection, gets tuned with evidence, and moves toward prevention safely.',
 'publish': True,
 'tags': ['Azure', 'WAF', 'Front Door', 'Security']}
