"""
Blog Post 165: How to Plan AKS Node Pools for Mixed Workloads
"""

BLOG_POST = {'title': 'How to Plan AKS Node Pools for Mixed Workloads',
 'coverImage': 'https://static.wixstatic.com/media/32fce1_6c1cc8bc82db46b998b61dc5273d7d99~mv2.png',
 'content': 'A useful Azure how-to should end with something you can operate, not just something '
            'that deployed once.\n'
            '\n'
            'This guide walks through **an AKS cluster with node pools that separate system, user, '
            'and specialized workloads** using **Azure Kubernetes Service**.\n'
            '\n'
            '## When To Use This Pattern\n'
            '\n'
            'Use this pattern when you need a repeatable way to configure **Azure Kubernetes '
            'Service** and explain the decision to another engineer later.\n'
            '\n'
            'The goal is not to click through the portal as fast as possible.\n'
            '\n'
            'The goal is to understand the resource, the security boundary, the validation step, '
            'and the operational owner.\n'
            '\n'
            '## Before You Start\n'
            '\n'
            'Confirm the subscription, resource group, region, naming standard, tags, and identity '
            'model before creating anything.\n'
            '\n'
            'Also confirm whether this change affects production traffic, data access, cost, or '
            'compliance.\n'
            '\n'
            'If it does, create the change record first and make rollback expectations explicit.\n'
            '\n'
            '## Steps\n'
            '\n'
            '1. Keep the system node pool dedicated to core cluster services.\n'
            '\n'
            '2. Create user node pools for application workloads.\n'
            '\n'
            '3. Use labels, taints, and tolerations to steer workloads intentionally.\n'
            '\n'
            '4. Add specialized pools for GPU, memory-heavy, or compliance-sensitive workloads.\n'
            '\n'
            '5. Review upgrade, autoscaling, and quota behavior per node pool.\n'
            '\n'
            '## Validate The Work\n'
            '\n'
            'Inspect pod placement and simulate node pool scale or drain operations before calling '
            'the design production-ready.\n'
            '\n'
            'Validation is where many cloud guides get weak.\n'
            '\n'
            'Do not stop at a green deployment screen. Test from the same network, identity, '
            'pipeline, or application path that will use the service in real life.\n'
            '\n'
            '## Production Notes\n'
            '\n'
            'A single general-purpose node pool is easy at first and painful later. Separate noisy '
            'or sensitive workloads early.\n'
            '\n'
            'Add tags, diagnostic settings, alert ownership, and documentation before calling the '
            'work finished.\n'
            '\n'
            'If the resource is important enough to deploy, it is important enough to monitor.\n'
            '\n'
            '## Common Mistakes\n'
            '\n'
            'The first mistake is deploying without knowing the owner.\n'
            '\n'
            'The second mistake is skipping least privilege because a broad role is faster.\n'
            '\n'
            'The third mistake is forgetting DNS, routing, logging, or cost review until after the '
            'first incident.\n'
            '\n'
            'Keep the implementation small, but make the operating model clear.\n'
            '\n'
            '## Bottom Line\n'
            '\n'
            '**Azure Kubernetes Service** is easier to support when the design is intentional.\n'
            '\n'
            'Build it with a clear purpose, validate the real path, and leave behind enough '
            'documentation that the next engineer can understand the decision.\n'
            '\n'
            '## Sources\n'
            '\n'
            'Microsoft Learn: https://learn.microsoft.com/en-us/azure/aks/create-node-pools\n'
            '\n'
            '---\n'
            '\n'
            "*Stay radical, stay curious, and keep pushing the boundaries of what's possible in "
            'the cloud.*\n'
            '\n'
            '**Chriz**\n'
            '*Beyond Cloud with Chriz*',
 'excerpt': 'A practical Azure how-to for Azure Kubernetes Service: an AKS cluster with node pools '
            'that separate system, user, and specialized workloads.',
 'publish': True,
 'tags': ['Azure', 'AKS', 'Node Pools', 'Kubernetes']}
