"""
Blog Post 162: How to Put Azure Front Door Premium in Front of a Private App Service Origin
"""

BLOG_POST = {'title': 'How to Put Azure Front Door Premium in Front of a Private App Service Origin',
 'coverImage': 'https://static.wixstatic.com/media/32fce1_6c1cc8bc82db46b998b61dc5273d7d99~mv2.png',
 'content': 'A useful Azure how-to should end with something you can operate, not just something '
            'that deployed once.\n'
            '\n'
            'This guide walks through **a public edge with WAF and a private origin path to App '
            'Service** using **Azure Front Door**.\n'
            '\n'
            '## When To Use This Pattern\n'
            '\n'
            'Use this pattern when you need a repeatable way to configure **Azure Front Door** and '
            'explain the decision to another engineer later.\n'
            '\n'
            'The goal is not to click through the portal as fast as possible.\n'
            '\n'
            'The goal is to understand the resource, the security boundary, the validation step, '
            'and the operational owner.\n'
            '\n'
            '## Before You Start\n'
            '\n'
            'Confirm the subscription, resource group, region, naming standard, tags, and identity '
            'model before creating anything.\n'
            '\n'
            'Also confirm whether this change affects production traffic, data access, cost, or '
            'compliance.\n'
            '\n'
            'If it does, create the change record first and make rollback expectations explicit.\n'
            '\n'
            '## Steps\n'
            '\n'
            '1. Create an Azure Front Door Premium profile and endpoint.\n'
            '\n'
            '2. Add the App Service origin and enable Private Link for the sites subresource.\n'
            '\n'
            '3. Approve the pending private endpoint connection on the App Service side.\n'
            '\n'
            '4. Route traffic through the origin group and configure health probes.\n'
            '\n'
            '5. Disable or restrict direct public access to the App Service origin after '
            'validation.\n'
            '\n'
            '## Validate The Work\n'
            '\n'
            'Test the Front Door endpoint, confirm the origin is healthy, and verify the app is no '
            'longer reachable directly except through the approved path.\n'
            '\n'
            'Validation is where many cloud guides get weak.\n'
            '\n'
            'Do not stop at a green deployment screen. Test from the same network, identity, '
            'pipeline, or application path that will use the service in real life.\n'
            '\n'
            '## Production Notes\n'
            '\n'
            'Do not mix public and private origins in the same origin group. Keep the public edge '
            'and private origin model clean.\n'
            '\n'
            'Add tags, diagnostic settings, alert ownership, and documentation before calling the '
            'work finished.\n'
            '\n'
            'If the resource is important enough to deploy, it is important enough to monitor.\n'
            '\n'
            '## Common Mistakes\n'
            '\n'
            'The first mistake is deploying without knowing the owner.\n'
            '\n'
            'The second mistake is skipping least privilege because a broad role is faster.\n'
            '\n'
            'The third mistake is forgetting DNS, routing, logging, or cost review until after the '
            'first incident.\n'
            '\n'
            'Keep the implementation small, but make the operating model clear.\n'
            '\n'
            '## Bottom Line\n'
            '\n'
            '**Azure Front Door** is easier to support when the design is intentional.\n'
            '\n'
            'Build it with a clear purpose, validate the real path, and leave behind enough '
            'documentation that the next engineer can understand the decision.\n'
            '\n'
            '## Sources\n'
            '\n'
            'Microsoft Learn: https://learn.microsoft.com/en-us/azure/frontdoor/private-link\n'
            '\n'
            '---\n'
            '\n'
            "*Stay radical, stay curious, and keep pushing the boundaries of what's possible in "
            'the cloud.*\n'
            '\n'
            '**Chriz**\n'
            '*Beyond Cloud with Chriz*',
 'excerpt': 'A practical Azure how-to for Azure Front Door: a public edge with WAF and a private '
            'origin path to App Service.',
 'publish': True,
 'tags': ['Azure', 'Front Door', 'Private Link', 'App Service']}
