"""
Blog Post 173: How to Decide When Azure Cosmos DB Serverless Fits
"""

BLOG_POST = {'title': 'How to Decide When Azure Cosmos DB Serverless Fits',
 'coverImage': 'https://static.wixstatic.com/media/32fce1_6c1cc8bc82db46b998b61dc5273d7d99~mv2.png',
 'content': 'A useful Azure how-to should end with something you can operate, not just something '
            'that deployed once.\n'
            '\n'
            'This guide walks through **a practical decision framework for choosing serverless '
            'instead of provisioned throughput** using **Azure Cosmos DB**.\n'
            '\n'
            '## When To Use This Pattern\n'
            '\n'
            'Use this pattern when you need a repeatable way to configure **Azure Cosmos DB** and '
            'explain the decision to another engineer later.\n'
            '\n'
            'The goal is not to click through the portal as fast as possible.\n'
            '\n'
            'The goal is to understand the resource, the security boundary, the validation step, '
            'and the operational owner.\n'
            '\n'
            '## Before You Start\n'
            '\n'
            'Confirm the subscription, resource group, region, naming standard, tags, and identity '
            'model before creating anything.\n'
            '\n'
            'Also confirm whether this change affects production traffic, data access, cost, or '
            'compliance.\n'
            '\n'
            'If it does, create the change record first and make rollback expectations explicit.\n'
            '\n'
            '## Steps\n'
            '\n'
            '1. Estimate request volume, storage, burst patterns, and latency expectations.\n'
            '\n'
            '2. Choose serverless for intermittent or unpredictable workloads that do not need '
            'reserved throughput.\n'
            '\n'
            '3. Use provisioned throughput when sustained high volume or predictable capacity is '
            'required.\n'
            '\n'
            '4. Test partition key design before focusing on pricing.\n'
            '\n'
            '5. Monitor request units and throttling after launch.\n'
            '\n'
            '## Validate The Work\n'
            '\n'
            'Load test realistic access patterns and compare cost and throttling behavior against '
            'provisioned throughput.\n'
            '\n'
            'Validation is where many cloud guides get weak.\n'
            '\n'
            'Do not stop at a green deployment screen. Test from the same network, identity, '
            'pipeline, or application path that will use the service in real life.\n'
            '\n'
            '## Production Notes\n'
            '\n'
            'Serverless is a billing and capacity model, not a substitute for good partition '
            'design.\n'
            '\n'
            'Add tags, diagnostic settings, alert ownership, and documentation before calling the '
            'work finished.\n'
            '\n'
            'If the resource is important enough to deploy, it is important enough to monitor.\n'
            '\n'
            '## Common Mistakes\n'
            '\n'
            'The first mistake is deploying without knowing the owner.\n'
            '\n'
            'The second mistake is skipping least privilege because a broad role is faster.\n'
            '\n'
            'The third mistake is forgetting DNS, routing, logging, or cost review until after the '
            'first incident.\n'
            '\n'
            'Keep the implementation small, but make the operating model clear.\n'
            '\n'
            '## Bottom Line\n'
            '\n'
            '**Azure Cosmos DB** is easier to support when the design is intentional.\n'
            '\n'
            'Build it with a clear purpose, validate the real path, and leave behind enough '
            'documentation that the next engineer can understand the decision.\n'
            '\n'
            '## Sources\n'
            '\n'
            'Microsoft Learn: https://learn.microsoft.com/en-us/azure/cosmos-db/serverless\n'
            '\n'
            '---\n'
            '\n'
            "*Stay radical, stay curious, and keep pushing the boundaries of what's possible in "
            'the cloud.*\n'
            '\n'
            '**Chriz**\n'
            '*Beyond Cloud with Chriz*',
 'excerpt': 'A practical Azure how-to for Azure Cosmos DB: a practical decision framework for '
            'choosing serverless instead of provisioned throughput.',
 'publish': True,
 'tags': ['Azure', 'Cosmos DB', 'Serverless', 'Database']}
